### ISSUE TITLE
Maybe bug: User prompted for Filesystem access

### ISSUE THREAD

**Issue by lincolnthree** [mapiacompany/capacitor-codepush#12]
Thanks so much for getting this plugin converted to Capacitor! 

### Description

After installing and configuring the code-push plugin, doing some preliminary testing seems to show that users are required to accept the following permission prompt:

![image](https://user-images.githubusercontent.com/362329/109706565-1ccd5a00-7b67-11eb-9f73-91296f3913bf.png)

Is this normal, or have I done something wrong? It seems this plugin should be able to function without writing to External storage, but I am not an Android permissions expert.

### Reproduction

1. Ensure update is available in AppCenter
2. Run the app with this plugin installed
3. Call `codePushUtil.sync()`

### Additional Information

* cordova-plugin-code-push version: This repo
* List of installed plugins: 
```
[info] Found 20 Capacitor plugins for ios:
       @capacitor-community/http@0.3.0
       @capacitor/app@0.3.3
       @capacitor/app-launcher@0.5.3
       @capacitor/browser@0.4.3
       @capacitor/clipboard@0.4.3
       @capacitor/device@0.5.3
       @capacitor/dialog@0.4.3
       @capacitor/filesystem@0.4.0
       @capacitor/geolocation@0.4.0
       @capacitor/haptics@0.3.3
       @capacitor/keyboard@0.5.3
       @capacitor/local-notifications@0.4.0
       @capacitor/network@0.4.3
       @capacitor/push-notifications@0.3.3
       @capacitor/share@0.5.0
       @capacitor/splash-screen@0.3.3
       @capacitor/status-bar@0.4.3
       capacitor-codepush@1.0.0
       capacitor-firebase-auth@2.3.5
       capacitor-rate-app@1.0.0
[info] Found 2 Cordova plugins for ios:
       cordova-plugin-file-opener2@3.0.5
       cordova-plugin-purchase@10.5.3
```

* Capacitor version: 3.0.0-beta.6
* iOS/Android/Windows version: iOS 14, Android 11
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by leo6104** [comment]
It might be related with https://github.com/ionic-team/capacitor-plugins/issues/248 .

Can you try with @capacitor/filesystem 0.5.1 ?

**Comment by lincolnthree** [comment]
@leo6104 I think this solved the issue. Running some final tests but I think it's working without prompt on 0.5.1.

**Comment by lincolnthree** [comment]
Closing this as I believe it is resolved. Thanks!
