### ISSUE TITLE
iOS: Updates extract/say they are installed, but are always rolled back

### ISSUE THREAD

**Issue by lincolnthree** [mapiacompany/capacitor-codepush#18]
### Description

So, I'm not exactly sure how to report on this one. I've been stuck on it for a few days. I'm wondering if anyone else has observed this behavior.

It seems as if the updates are downloaded and extracted correctly, but when the app restarts, the update is not activated and nothing has changed.

The .sync() method is called again, reporting that the same update is available, but has been rolled back already.

### Reproduction

1. Install app to local iOS device or simulator
2. Make sure an update is ready on Codepush for the installed bundle version
3. Start the app & observe logs
4. Ensure app calls `codePush.sync()`
5. Update should install and "waiting until reloaded/restarted" (unless immediate activation is set, at which point it restarts right away)

Screenshot of device filesystem at this point:

Deploy:
![image](https://user-images.githubusercontent.com/362329/110212902-974df080-7e6b-11eb-9ec4-fe3ade08950e.png)

Download:
![image](https://user-images.githubusercontent.com/362329/110212916-a0d75880-7e6b-11eb-9fef-0b9b2741cd83.png)

6. Restart to activate the update (the update will not be activated at this point, but... continue on)

7. Ensure application calls "codePush.notifyApplicationReady()"

Device will log:
```
[Warning] UPDATE: Committing update. (Will not be rolled back.) (vendor-es2015.js, line 86501)
[Warning] UPDATE: Checking for update. (vendor-es2015.js, line 86501)
```

8. Ensure app calls `codePush.sync()` again to verify status
9. The update will not be available but not activated/not installing, because status is "previously rolled back"

Device will log:
```
[Log] [CodePush] An update is available. {"isDownloading":false,"appVersion":"10.0.6","deploymentKey":"XXXXXXXXXXX","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/XXXXXXXXXXX","isMandatory":false,"label":"v1","packageHash":"XXXXXXXXXXX","packageSize":7092826,"failedInstall":1} (vendor-es2015.js, line 86501)
[Log] [CodePush] An update is available, but it is being ignored due to have been previously rolled back. (vendor-es2015.js, line 86501)
```

Screenshot of device filesystem at this point:

![image](https://user-images.githubusercontent.com/362329/110212993-12170b80-7e6c-11eb-9c5f-c89c24e27213.png)

### Additional Information

* cordova-plugin-code-push version: Latest version from github #capacitor branch.

(The more info the faster we will be able to address it!)

**Comment by lincolnthree** [comment]
I see this message when debugging `CodePush.m`. Not sure if it is related:

```
[WKWebView loadRequest:] must be used from main thread only
```

The value of url looks correct: `/Documents/codepush/deploy/versions/a8d1fe720898460b27442176f206ea1e0e112a057d1dbb2252dec8d424b8fd92/www/index.html`

**Comment by lincolnthree** [comment]
When app is re-launched after install, it seems like the result of CodePushPackageManager.m:getPendingInstall() is nil

It is not locating the deployed installation.

**Comment by lincolnthree** [comment]
Possibly related to this warning in XCode for `save/getPendingInstall()` methods?

```
'archivedDataWithRootObject:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: instead
```

**Comment by lincolnthree** [comment]
Found the issue, the installMode flag seems to be "IMMEDIATE" regardless of what is passed to `CodePush.m:install` on line 177.

The code is attempting to retrieve `NSNumber` data types as `NSString` which returns nil:

```
- (void)install:(CAPPluginCall *)call {
    NSString* location = [self getString:call field:@"startLocation" defaultValue:nil];
    NSString* installModeString = [self getString:call field:@"installMode" defaultValue:IMMEDIATE];
```

Sending a PR.

**Comment by lincolnthree** [comment]
PR: https://github.com/mapiacompany/capacitor-codepush/pull/19

**Comment by leo6104** [comment]
> [WKWebView loadRequest:] must be used from main thread only

This error can cause rendering performance issue during codePush.sync() 

Good point!

**Comment by leo6104** [comment]
It still have this issue. 

> 2021-03-08 00:47:53.633542+0900 App[12713:1076311] [connection] nw_socket_handle_socket_event [C10.1:3] Socket SO_ERROR [54: Connection reset by peer]
> 2021-03-08 00:47:53.633792+0900 App[12713:1076311] [connection] nw_read_request_report [C10] Receive failed with error "Connection reset by peer"
> 2021-03-08 00:47:53.634633+0900 App[12713:1075988] WF: _userSettingsForUser : (null)
> 2021-03-08 00:47:53.634735+0900 App[12713:1075988] WF: _WebFilterIsActive returning: NO
> 2021-03-08 00:47:57.486468+0900 App[12713:1076311] [connection] nw_write_request_report [C10] Send failed with error "Broken pipe"
> 2021-03-08 00:47:57.487461+0900 App[12713:1075988] [Process] 0x7fe39104ea20 - [pageProxyID=6, webPageID=7, PID=12719] WebPageProxy::processDidBecomeUnresponsive:


In my case, it also says "Installed" but it broken with internal problem.

**Comment by leo6104** [comment]
It seems loadURL function implementation has  a problem. I change the loadPackage implementation (which invoke loadURL) like below. 

```
- (BOOL)loadPackage:(NSString*)packageLocation {
    NSURL* URL = [self getStartPageURLForLocalPackage:packageLocation];
    if (URL) {
        [self setServerBasePath:URL.path];
        return YES;
    }

    return NO;
}
```

Instead of calling loadURL function, i just call setServerBasePath. And then it reload the contents to new one. (might be progress to next step) But, i got new error. 

In XCode log, it says 
```
⚡️  [error] - ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'uc.notifyApplicationReady')
```

`self setServerBasePath:URL` reload content in webview. but it doesn't inject Native plugin proxy object correctly. (CodePush) 
I will figure out how to inject proxy object from capacitor core (they might call some functions to inject plugin proxy object)

**Comment by leo6104** [comment]
Oh it was just my legacy codepush deployments problem. 

I remove all codepush deployments & create new deployments and latest package all works.

**Comment by lincolnthree** [comment]
@leo6104 Do you feel this bug is resolved? Interested if there's something more that needs to happen.

**Comment by leo6104** [comment]
@lincolnthree I think we can close this issue. I will keep eye on next release of @capacitor/*. 👍
