### ISSUE TITLE
[Critical] Android native updates do not override downloaded CodePush bundle for prior versions.

### ISSUE THREAD

**Issue by lincolnthree** [mapiacompany/capacitor-codepush#23]
### Description

When app is updated via streaming, if a CodePush update was previously downloaded, it will still be used instead of using the new native bundled code.

### Reproduction

1. Install app version 1.0.0
2. Prepare a codepush release for 1.0.0 and make sure it is installed via codepush.
2. Stream / update app version 1.0.1 via native build (`adb install -r path/to/release.apk`)
3. The app native version will be 1.0.1, but the code running will still be 1.0.0 (from codepush)

This seems incorrect, as the bundle should use the newer code from the native install/update.

Thoughts on this?

### Additional Information

* cordova-plugin-code-push version: Latest
* iOS/Android/Windows version: Android 11 (have not tested with others)
* Does this reproduce on a debug build or release build? Release build streamed via ADB, not sure about prod install from Play Store yet.
* Does this reproduce on a simulator, or only on a physical device? Physical device.

**Comment by lincolnthree** [comment]
Confirmed this issues does also happen when apps update through the Play Store, natively via the Android app update process.

It can be easily reproduced using the `adb` command in the issue above.

**Comment by lincolnthree** [comment]
@leo6104 Have you seen this issue happen on any of your devices? I don't know what causes it. Any tips?

**Comment by lincolnthree** [comment]
Update. This seems to be caused because `Utilities.java` cannot resolve `CODE_PUSH_APK_BUILD_TIME` from `strings.xml`, which I assume would have been generated by some Cordova build step that has not been migrated to this capacitor project. @leo6104 Does that sound possible?:

Utilities.java
```
public static long getApkBuildTime(Context context) {

        Long millis;

        try {
            //replace double quotes needed for correct restoration of long value from strings.xml
            //https://github.com/Microsoft/cordova-plugin-code-push/issues/264
            millis = parseLong(context.getString(
                context.getResources().getIdentifier("CODE_PUSH_APK_BUILD_TIME", "string", context.getPackageName())
            ).replaceAll("\"",""));
        } catch(Resources.NotFoundException e) {
            return -1;
        }

        return millis;
    }
```

**Comment by leo6104** [comment]
@lincolnthree Thank you for reporting the issue. 

It seems CODE_PUSH_APK_BUILD_TIME injected from `build-extras.gradle` file and `build-extras.gradle` file is only compatible with cordova CLI. 

```
android.buildTypes.each {
   // to prevent incorrect long value restoration from strings.xml we need to wrap it with double quotes
   // https://github.com/Microsoft/cordova-plugin-code-push/issues/264
   it.resValue "string", "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
}
```

Let's move this implementation to `build.gradle` and remove build-extras.gradle.

**Comment by lincolnthree** [comment]
@leo6104 YES! I think this is the issue. Awesome.

I also found an issue with NumberFormatException crashing apps in some cases. I will send a PR with that fix. I'm not very familiar with build.gradle. Which file do we put that in?

**Comment by lincolnthree** [comment]
Oh I see. There is already a build.gradle file. Where should it go in that file? I'll make some attempts.

**Comment by leo6104** [comment]
@lincolnthree I did a commit for build.gradle (https://github.com/mapiacompany/capacitor-codepush/commit/c9a656f7f38c378dece68f1d07cd8587a20bf9ab) Can you check with my commit?

**Comment by lincolnthree** [comment]
@leo6104 Ok checking. That looks like what I just tried but I could not verify that the build time was actually generated. One moment.

**Comment by leo6104** [comment]
@lincolnthree When i put the implementation in build.gradle, it create gradleResValues.xml like this.

![image](https://user-images.githubusercontent.com/7777929/111873601-72fa2400-89d4-11eb-91dc-346669cdbed6.png)

After i build and run on emulator, i search `CODE_PUSH_APK_BUILD_TIME` keyword in project and found it.

**Comment by lincolnthree** [comment]
@leo6104 Interesting. Maybe this only runs when generating an APK, and not when building for emulator?

```
sharktop:topdecked-unified lincoln$ ls android/app/build/generated/res/resValues/debug/values
ls: android/app/build/generated/res/resValues/debug/values: No such file or directory
```

**Comment by lincolnthree** [comment]
Oh, you said it runs on emulator... doing a full rebuild.

**Comment by lincolnthree** [comment]
@leo6104 Btw are you on discord?

**Comment by lincolnthree** [comment]
File not being generated for me :/

**Comment by lincolnthree** [comment]
@leo6104 Interesting. It's generated in the node_modules folder, not the project itself.

**Comment by lincolnthree** [comment]
@leo6104 SUCCESS! Nice job.

**Comment by lincolnthree** [comment]
Looks like it is fixed! I have tested with the emulator and it is working!

**Comment by Clovel** [comment]
Perhaps we should close this issue ?
