### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by 2693252993** [mapiacompany/capacitor-codepush#26]
### Description
The following error occurred in the console when I started the app
![image](https://user-images.githubusercontent.com/27254047/112093070-c6869080-8bd3-11eb-9afa-b51f5cd7b29a.png)
![image](https://user-images.githubusercontent.com/27254047/112093122-d4d4ac80-8bd3-11eb-9188-5d1e2c833a88.png)

my main.ts
![image](https://user-images.githubusercontent.com/27254047/112093331-31d06280-8bd4-11eb-8344-886c3a4a0d62.png)

my package.json
![image](https://user-images.githubusercontent.com/27254047/112093395-47458c80-8bd4-11eb-8751-08a80826fbe8.png)

I'm running on Android.   Can you help me solve this problem?

**Comment by uioporqwerty** [comment]
Experiencing this issue as well. Were you able to resolve this @2693252993?

**Comment by 2693252993** [comment]
@uioporqwerty  make sure  the "@capacitor-community/http"  >=  "^1.0.0-alpha.1",
`npm i  @capacitor-community/http@next`
It's work
