### ISSUE TITLE
Using with other capacitor versions

### ISSUE THREAD

**Issue by theZaX** [mapiacompany/capacitor-codepush#32]
Does this only work on capacitor 3? I'm interested in implementing with this but the docs are 100% clear on what version of capacitor you need to use. Do I need to upgrade to capacitor 3?

I tried on capacitor 2 and it wouldn't compile in Android studio. When I googled the error message it talked about incompatibility with capacitor 2. I can share more info if that is not the expected behavior.

**Comment by nonsenseless** [comment]
It’s capacitor 3 only. You can check package.json to see be capacitor version it’s pinned to.

**Comment by leo6104** [comment]
@theZaX It is difficult to support code-push in Capacitor 2.

In Capacitor 2, 
1. there is no stable plugin for downloading www folder.
2. some of capacitor core module has bugs so i cannot fix it on these plugin itself.
