### ISSUE TITLE
Will this work in an ionic 5/capacitor 3/angular/firebase project?

### ISSUE THREAD

**Issue by metalllus** [mapiacompany/capacitor-codepush#46]
Just a quick question if this should work in an ionic 5/capacitor 3/angular/firebase project to have the same functionality as provided by Ionic Appflow Live Updates. Just to be sure if this is viable for my use case before I dive in deeper trying to implement it. Thank you 🙏 .

**Comment by nonsenseless** [comment]
Yes, it will provide support for the same kind of live updates that Ionic App Flow provides.

**Comment by metalllus** [comment]
@nonsenseless another quick question, when I create the app with the command
`appcenter apps create -d <appDisplayName> -o <operatingSystem>  -p <platform> `
what platform should I choose for iOS and Android to make it work, Cordova for both or...?

**Comment by nonsenseless** [comment]
Not a clue since I’ve always made the slots through the web ui. You’ll need
to create separate apps for both android and iOS though.

**Comment by metalllus** [comment]
@nonsenseless on the web ui you also have to select platform:
![2021-09-03_17-28-40](https://user-images.githubusercontent.com/48943750/132030439-cc35b007-a001-4b0e-81f4-f3ecb0a1e1dd.png)

**Comment by nonsenseless** [comment]
Okay, well, what kind of app do you *want* it to be? Pick that one.

**Comment by nonsenseless** [comment]
You’re probably going to want Cordova though if you’re using code push.

**Comment by metalllus** [comment]
@nonsenseless well in my case I am using Ionic/Capacitor and this plugin is using Capacitor, therefore I am not sure 100 percent sure Cordova is indeed the way to go for me.

**Comment by nonsenseless** [comment]
This plugin is forked specifically to work with capacitor. The web ui is
going off the assumptions of the stock plugin which uses Cordova; Cordova
is the closest match for your project.

**Comment by metalllus** [comment]
@nonsenseless thx for the help.
