### ISSUE TITLE
CodePush Error Could not get the package start page

### ISSUE THREAD

**Issue by metalllus** [mapiacompany/capacitor-codepush#47]
I am testing this on an Ionic/Capacitor/Angular/Firebase project, NOT Cordova.
What I have done so far:
1. Created new app with `appcenter apps create -d <appDisplayName> -o iOS -p Cordova`
2. Created new deployment with `appcenter codepush deployment add -a <ownerName>/<appName> Production` 
3. Built new app version ready for release with `ng build`
4. Released new version with `appcenter codepush release -a <ownerName>/<appName> -c ./PATH_TO_BUILD -m -t 1.0 -d Production`
5. The app displays the modal saying new version is available. I click continue to proceed with install.
6. During the install in Xcode I get the error `CodePush Error Could not get the package start page....`
7. I downloaded the update manually from the appcenter website to check it, unzipped it, it has the following file structure: all files are stored one directory, directory name is my angular project name, the files in this directory are all my built project files, everything seems absolutely fine, index.html is included.

If anyone has a suggestion where I got it wrong, please do let me know.

**Comment by veneliniliev** [comment]
how to solve the problem?

**Comment by ibrahimAboelsuod** [comment]
I am having the same problem, how did you sovle it?

**Comment by pilz97** [comment]
I have the same issue.

I read that it workes with cordova-android 9.0.0 but won't work with 10.x

Is there a way to get it working with android 10.x?
