### ISSUE TITLE
Cordova Codepush is shutting down

### ISSUE THREAD

**Issue by alexcroox** [mapiacompany/capacitor-codepush#59]
https://devblogs.microsoft.com/appcenter/announcing-apache-cordova-retirement/

**Comment by alexcroox** [comment]
@Clovel you seem pretty active on this fork. How would you feel about creating a generic client version that accepts a configured endpoint so people can roll/contribute their own server side versions?

**Comment by o-alexandrov** [comment]
Using Cordova setup on AppCenter would have been pointless, as Cordova support was only for preview w/o ability to build.
So while the idea to document a self-managed solution would be great, the mentioned AppCenter news has nothing to do with this particular project.

Some references how you should have configured AppCenter instead (as a native iOS / Android project):
- https://arielhernandezmusa.medium.com/building-ionic-capacitor-on-appcenter-fe0105bb02d1
- https://www.kevinboosten.dev/release-your-ionic-and-capacitor-app-via-appcenter

**Comment by alexcroox** [comment]
Ah excellent news, apologies I'm still waiting to implement this in a sprint but I've been following closely since the last project used Cordova CodePush and assumed it was the same setup in AppCenter. Thanks for the clarification!

**Comment by alexcroox** [comment]
@o-alexandrov what did you choose as your platform? I chose iOS / Objective-C/Swift in their web UI and got the following when trying to later add deployments keys;

➜  xxxx git:(feature/ota-native) appcenter codepush deployment add -a xxx/xxx-ios-sandbox Production
Error: [{"message":"Not Supported platform / OS combination: Objective-C-Swift / iOS"}]

**Edit: ignore me, I realise now your "choose native" message previously meant "choose React Native"**

**Comment by o-alexandrov** [comment]
@alexcroox please follow mentioned articles above.
Native means `iOS / Objective-C` and `Java / Kotlin`

**Comment by alexcroox** [comment]
Yeah I followed that originally and got the above error when trying to add deployment keys. Looking into it seems codepush is only for React Native / Cordova so selecting one of the other project types wont work.

**Comment by o-alexandrov** [comment]
Sorry, I misunderstood you.
If you want the OTA (codepush), you should pick React Native.
If you want the TestFlight/App Store or Google Play distribution, you should pick a native project.

You can have two AppCenter projects for the same app, one for the OTA and another one for the `Build`s to stores
