### ISSUE TITLE
Can not use `sync` method in script

### ISSUE THREAD

**Issue by sawaca96** [mapiacompany/capacitor-codepush#61]
### Description

I want to use CodePush in index.html.
But error occurred : `Unhandled Promise Rejection: Error: "CodePush.sync()" is not implemented on iOS`
```js
<script src="capacitor.js"></script>
<script>
async function onLoad() {
  const { Plugins } = Capacitor;
  const { CodePush } = Plugins;
  document.addEventListener(
    'deviceready',
    async function () {
      await CodePush.sync()
    },
    false
  );
  document.addEventListener(
    'resume',
    function () {
      ...
    },
    false
  );
  document.addEventListener(
    'pause',
    function () {
      ...
    },
    false
  );
}
</script>
...
<body onload="onLoad()">
``` 

So I checked CodePush object
but there is no `sync` method. also API is different from docs. 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/49309322/138556121-1532c20e-ecbf-4e98-9909-72ead2cd2577.png">

How can I solve this ? 

### Additional Information

I use vue2 and capacitor3

**Comment by alexcroox** [comment]
`const { CodePush } = Plugins;`

That doesn't look like Capacitor 3 code to me

**Comment by sawaca96** [comment]
@alexcroox then how to use CodePush in index.html ? any suggestion or example ?

**Comment by tolutronics** [comment]
//capacitor v3
import { codePush } from 'capacitor-codepush';

**Comment by sawaca96** [comment]
Can't I use CodePush like the [comment](https://github.com/ionic-team/capacitor/discussions/3226#discussioncomment-35855)?

**Comment by tolutronics** [comment]
That style is for capacitor version 2,  but unfortunately, code push does not support capacitor version 2

**Comment by alexcroox** [comment]
@sawaca96 I had that `Error: "CodePush" plugin is not implemented on ios` error because although I had:

`@capacitor/device, @capacitor/dialog, @capacitor/filesystem` installed, I forgot to run `npx cap sync` after.

**Comment by sawaca96** [comment]
> That style is for capacitor version 2, but unfortunately, code push does not support capacitor version 2

Oh, Thanks. 

@alexcroox 
now I use codepush like below
```js
import { codePush, InstallMode } from @capacito-codepush
...
await codePush.sync({
  installMode: InstallMode.ON_NEXT_RESUME
})
```
