### ISSUE TITLE
App Center - Apache Cordova Retirement

### ISSUE THREAD

**Issue by nick-krantz** [mapiacompany/capacitor-codepush#63]
App Center recently announced in this [blog post](https://devblogs.microsoft.com/appcenter/announcing-apache-cordova-retirement/) that they are retiring Apache Cordova. This plugin is a fork of the [microsoft/cordova-plugin-code-push](https://github.com/microsoft/cordova-plugin-code-push), does this impact any of the functionality of the existing plugin? Will it continue to function with Capacitor?

Thanks!

**Comment by o-alexandrov** [comment]
Duplicate of #59 and #62

**Comment by nick-krantz** [comment]
Not sure how I didn't see those before! Thank you~
