### ISSUE TITLE
Cordova will be retired from App Center starting April 1st 2022

### ISSUE THREAD

**Issue by DanProudfoot** [mapiacompany/capacitor-codepush#65]
Just saw this when I logged in recently:

https://devblogs.microsoft.com/appcenter/announcing-apache-cordova-retirement/

I don't know if it affects this plugin, but as I set up my project as a Cordova project on the App Center side, it's worth mentioning.

**Comment by alexcroox** [comment]
Please check the last 3 closed issues

**Comment by DanProudfoot** [comment]
Oops sorry, great stuff.
