### ISSUE TITLE
[NOT A ISSUE] AppCenter CodePush Backend Alternative

### ISSUE THREAD

**Issue by ludufre** [mapiacompany/capacitor-codepush#66]
Hi, since Cordova retirement on AppCenter and per consequence Capacitor, I started looking for an backend alternative.

I almost started one from scratch, but I found an [old (dated 2019) repository](https://github.com/lisong/code-push-server) made by a guy and [one fork with some commits](https://github.com/shm-open/code-push-server) but outdated too (the most recents commits are dependences only). It's pretty outdated since need to use `code-push-cli@2.1.9`, but I managed to make it work with latest `cordova-plugin-code-push@2.0.0` and `code-push@4.0.5` with little adjustments.

I'm currently self-hosting my own CodePush backend and already delivered 224 updates since Oct 30, without rollbacks so far. (I have a small base of users :/)

Since the backend normally works with CodePush and Capacitor I believe it will be a good point to revive that project.

I'm thinking some thing like Integration with OneDrive as "CDN" to host the updates or like so.

**Comment by ludufre** [comment]
My fork: https://github.com/ludufre/code-push-server

**Comment by ludufre** [comment]
@leo6104

**Comment by alexcroox** [comment]
I _love_ alternatives for the backend server, but just a heads-up the Cordova SDK retirement announcement doesn't impact this Capacitor plugin. Just choose React Native in the Codepush website and away you go (I'm using Capacitor v3 + Vue2 in my app with this method).

**Comment by ludufre** [comment]
Oh god. I'm feeling so stupid right now. I didn't had noticed that using others platforms works. By the way, I'm still using Cordova, so not the all time was lost...

**Comment by alexcroox** [comment]
Don't be, it's much better to have a self hosted alternative to MS Codepush server so I'll be following along closely!

**Comment by bazuka5801** [comment]
AppCenter React Native CodePush is good replacement, but look at these lines of code:
https://github.com/microsoft/appcenter-cli/blob/f4f9b8f5d2dd0d3988977ed6efa412e3320ff141/src/commands/codepush/lib/codepush-release-command-base.ts#L114-L123

`appcenter-cli` will zip `www` to `CodePush` folder ignoring `-c ios/app/app/public` argument

I modified this [cli](https://github.com/bazuka5801/appcenter-cli) (ignoring the lines above), you can install it with `yarn global add @bazumax/appcenter-cli` (after removing the original appcenter-cli)

**Comment by itshazlan** [comment]
@bazuka5801 should i reinstall appcenter cli with your version to avoid that above-mentioned issue?

**Comment by bazuka5801** [comment]
@itshazlan Yes, It will be fix for this issue
